var array__example_8nss =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md127", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md128", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md129", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md130", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md131", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md132", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md133", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md134", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md145", null ],
    [ "Example", "group__damage.html#autotoc_md147", null ],
    [ "Environment Variables", "group__diagnostics.html#autotoc_md148", null ],
    [ "Memory Sanitizer", "group__diagnostics.html#autotoc_md149", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md150", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md151", [
      [ "Dependencies", "group__dotnet.html#autotoc_md152", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md153", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md154", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md155", [
        [ "Sample", "group__nwnx.html#autotoc_md135", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md156", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md157", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md158", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md159", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md160", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md161", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md162", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md163", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md164", [
      [ "NWN types", "group__dotnet.html#autotoc_md165", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md166", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md167", null ],
      [ "Closures", "group__dotnet.html#autotoc_md168", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md169", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md170", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md171", null ],
    [ "Events", "group__elc.html#autotoc_md172", null ],
    [ "Example Script", "group__elc.html#autotoc_md173", null ],
    [ "Notes", "group__experimental.html#autotoc_md267", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md268", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md269", null ],
    [ "Setup", "group__feat.html#autotoc_md270", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md271", [
      [ "AB", "group__feat.html#autotoc_md272", null ],
      [ "ABILITY", "group__feat.html#autotoc_md274", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md276", null ],
      [ "AC", "group__feat.html#autotoc_md278", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md280", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md282", null ],
      [ "BONUSSPELL", "group__feat.html#autotoc_md284", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md286", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md288", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md290", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md292", null ],
      [ "HASTE", "group__feat.html#autotoc_md294", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md296", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md298", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md300", null ],
      [ "SAVE", "group__feat.html#autotoc_md302", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md304", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md306", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md308", null ],
      [ "SEEINVISIBLE", "group__feat.html#autotoc_md310", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md312", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md314", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md316", null ],
      [ "TRUESEEING", "group__feat.html#autotoc_md318", null ],
      [ "ULTRAVISION", "group__feat.html#autotoc_md320", null ],
      [ "VISUALEFFECT", "group__feat.html#autotoc_md322", null ]
    ] ],
    [ "Introduction", "group__http.html#autotoc_md324", null ],
    [ "Environment Variables", "group__http.html#autotoc_md325", null ],
    [ "Setup", "group__http.html#autotoc_md326", [
      [ "Client", "group__http.html#autotoc_md327", null ],
      [ "Server", "group__http.html#autotoc_md328", null ],
      [ "RPC", "group__http.html#autotoc_md329", null ]
    ] ],
    [ "Events", "group__http.html#autotoc_md330", [
      [ "Server Event Setup", "group__http.html#autotoc_md331", null ],
      [ "RPC Event Setup", "group__http.html#autotoc_md332", null ]
    ] ],
    [ "Client Usage", "group__http.html#autotoc_md333", [
      [ "JSON Helper", "group__http.html#autotoc_md334", null ],
      [ "Example Client Requests", "group__http.html#autotoc_md335", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md336", null ],
    [ "Quick start", "group__lua.html#autotoc_md337", [
      [ "Docker", "group__lua.html#autotoc_md338", null ],
      [ "Native", "group__lua.html#autotoc_md339", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md340", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md341", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md342", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md343", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md344", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md345", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md346", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md347", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md348", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md349", null ],
    [ "Environment Variables", "group__nostack.html#autotoc_md350", [
      [ "NWNX_NOSTACK_*", "group__nostack.html#autotoc_md351", null ],
      [ "NWNX_NOSTACK_*_DEFAULT_TYPE", "group__nostack.html#autotoc_md352", null ],
      [ "NWNX_NOSTACK_SEPARATE_INVALID_OID_EFFECTS", "group__nostack.html#autotoc_md353", null ]
    ] ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md354", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md355", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md357", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md358", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md359", null ],
    [ "Setup", "group__race.html#autotoc_md360", [
      [ "The 2da Method", "group__race.html#autotoc_md361", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md362", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md363", [
      [ "AB", "group__race.html#autotoc_md364", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md367", null ],
      [ "AC", "group__race.html#autotoc_md370", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md373", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md376", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md379", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md382", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md385", null ],
      [ "FEAT", "group__race.html#autotoc_md388", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md391", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md394", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md397", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md400", null ],
      [ "RACE", "group__race.html#autotoc_md403", null ],
      [ "REGENERATION", "group__race.html#autotoc_md406", null ],
      [ "SAVE", "group__race.html#autotoc_md409", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md412", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md415", null ],
      [ "SKILL", "group__race.html#autotoc_md418", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md421", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md424", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md427", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md430", null ],
    [ "Setup", "group__redis.html#autotoc_md431", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md432", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md433", [
      [ "Moving on", "group__redis.html#autotoc_md434", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md435", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md436", null ],
    [ "Sample Include", "group__rename.html#autotoc_md437", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md438", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md439", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md440", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md447", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md448", null ],
    [ "Migration", "group__sql.html#autotoc_md452", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md453", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md454", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md455", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md456", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md457", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md458", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md459", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md460", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md461", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md462", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md463", null ],
    [ "Notes", "group__tileset.html#autotoc_md464", null ],
    [ "Simple Example", "group__tileset.html#autotoc_md465", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md466", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md467", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md468", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md469", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md470", null ],
      [ "NWNX_TWEAKS_LANGUAGE_OVERRIDE", "group__tweaks.html#autotoc_md471", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md472", null ],
    [ "Function Documentation and Examples", "group__weapon.html#autotoc_md473", null ],
    [ "Available functions", "group__weapon.html#autotoc_md474", null ],
    [ "Example for Critical Event Script", "group__weapon.html#autotoc_md475", null ],
    [ "Limitations", "group__webhook.html#autotoc_md476", null ],
    [ "Example usage", "group__webhook.html#autotoc_md477", null ],
    [ "Log", "array__example_8nss.html#a71f6011f9c84f74acca8b63d03303cb6", null ],
    [ "TestArrayOnModule", "array__example_8nss.html#a15e56d0f9f40208818b8b5ac4bbfb3d0", null ],
    [ "TestArrayOnChicken", "array__example_8nss.html#a493a8ce1f39e3d96e3f2e7faf28f6fb7", null ],
    [ "TestNWNXArray", "array__example_8nss.html#a79f746b87354fb91846482213ec74929", null ],
    [ "main", "array__example_8nss.html#acdef7a1fd863a6d3770c1268cb06add3", null ]
];