var dir_ce92b3ebeae221968cfbe8aae0d60ffe =
[
    [ "Environment Variables", "group__nwnx.html#autotoc_md99", null ],
    [ "Console Commands", "group__nwnx.html#autotoc_md100", null ],
    [ "Custom Resman Definition File", "group__nwnx.html#autotoc_md101", null ],
    [ "Plugin Management", "group__nwnx.html#autotoc_md102", [
      [ "Environment Variable Configuration", "group__nwnx.html#autotoc_md103", null ],
      [ "Plugin Loading", "group__nwnx.html#autotoc_md104", null ],
      [ "Plugin Log Level", "group__nwnx.html#autotoc_md105", null ]
    ] ],
    [ "Core Functions For Plugin Developers", "group__nwnx.html#autotoc_md106", null ],
    [ "Environment Variables", "group__chat.html#autotoc_md117", null ],
    [ "Example", "group__damage.html#autotoc_md118", null ],
    [ "Environment Variables", "group__dotnet.html#autotoc_md119", null ],
    [ "Basic Setup", "group__dotnet.html#autotoc_md120", [
      [ "Dependencies", "group__dotnet.html#autotoc_md121", null ],
      [ "Compile managed code", "group__dotnet.html#autotoc_md122", null ],
      [ "Run NWNX with your DLL", "group__dotnet.html#autotoc_md123", null ],
      [ "Troubleshooting", "group__dotnet.html#autotoc_md124", [
        [ "Sample", "group__nwnx.html#autotoc_md107", null ],
        [ "libnethost.so", "group__dotnet.html#autotoc_md125", null ],
        [ "runtime config", "group__dotnet.html#autotoc_md126", null ],
        [ "Bootstrap()", "group__dotnet.html#autotoc_md127", null ]
      ] ]
    ] ],
    [ "How it works (basic)", "group__dotnet.html#autotoc_md128", [
      [ "<tt>OnStart</tt>", "group__dotnet.html#autotoc_md129", null ],
      [ "<tt>OnRunScript</tt>", "group__dotnet.html#autotoc_md130", null ],
      [ "<tt>OnMainLoop</tt>", "group__dotnet.html#autotoc_md131", null ],
      [ "Using NWScript in C", "group__dotnet.html#autotoc_md132", null ]
    ] ],
    [ "Advanced stuff", "group__dotnet.html#autotoc_md133", [
      [ "NWN types", "group__dotnet.html#autotoc_md134", null ],
      [ "Bootstrapping", "group__dotnet.html#autotoc_md135", null ],
      [ "OBJECT_SELF", "group__dotnet.html#autotoc_md136", null ],
      [ "Closures", "group__dotnet.html#autotoc_md137", null ],
      [ "Exceptions", "group__dotnet.html#autotoc_md138", null ]
    ] ],
    [ "Notes", "group__elc.html#autotoc_md139", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md140", null ],
    [ "Events", "group__elc.html#autotoc_md141", null ],
    [ "Example Script", "group__elc.html#autotoc_md142", null ],
    [ "Notes", "group__experimental.html#autotoc_md221", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md222", null ],
    [ "Environmental Variables", "group__feat.html#autotoc_md223", null ],
    [ "Setup", "group__feat.html#autotoc_md224", null ],
    [ "Feat Modifiers", "group__feat.html#autotoc_md225", [
      [ "AB", "group__feat.html#autotoc_md226", null ],
      [ "ABILITY", "group__feat.html#autotoc_md228", null ],
      [ "ABVSRACE", "group__feat.html#autotoc_md230", null ],
      [ "AC", "group__feat.html#autotoc_md232", null ],
      [ "ACVSRACE", "group__feat.html#autotoc_md234", null ],
      [ "ARCANESPELLFAILURE", "group__feat.html#autotoc_md236", null ],
      [ "CONCEALMENT", "group__feat.html#autotoc_md238", null ],
      [ "DMGREDUCTION", "group__feat.html#autotoc_md240", null ],
      [ "DMGRESIST", "group__feat.html#autotoc_md242", null ],
      [ "DMGIMMUNITY", "group__feat.html#autotoc_md244", null ],
      [ "IMMUNITY", "group__feat.html#autotoc_md246", null ],
      [ "MOVEMENTSPEED", "group__feat.html#autotoc_md248", null ],
      [ "REGENERATION", "group__feat.html#autotoc_md250", null ],
      [ "SAVE", "group__feat.html#autotoc_md252", null ],
      [ "SAVEVSRACE", "group__feat.html#autotoc_md254", null ],
      [ "SAVEVSTYPE", "group__feat.html#autotoc_md256", null ],
      [ "SAVEVSTYPERACE", "group__feat.html#autotoc_md258", null ],
      [ "SPELLIMMUNITY", "group__feat.html#autotoc_md260", null ],
      [ "SRCHARGEN", "group__feat.html#autotoc_md262", null ],
      [ "SRINCLEVEL", "group__feat.html#autotoc_md264", null ]
    ] ],
    [ "Environment Variables", "group__lua.html#autotoc_md266", null ],
    [ "Quick start", "group__lua.html#autotoc_md267", [
      [ "Docker", "group__lua.html#autotoc_md268", null ],
      [ "Native", "group__lua.html#autotoc_md269", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md270", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md271", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md272", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md273", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md274", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md275", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md276", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md277", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md278", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md279", null ],
    [ "Environment Variables", "group__optimizations.html#autotoc_md280", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md281", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md283", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md284", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md285", null ],
    [ "Setup", "group__race.html#autotoc_md286", [
      [ "The 2da Method", "group__race.html#autotoc_md287", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md288", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md289", [
      [ "AB", "group__race.html#autotoc_md290", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md293", null ],
      [ "AC", "group__race.html#autotoc_md296", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md299", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md302", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md305", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md308", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md311", null ],
      [ "FEAT", "group__race.html#autotoc_md314", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md317", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md320", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md323", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md326", null ],
      [ "RACE", "group__race.html#autotoc_md329", null ],
      [ "REGENERATION", "group__race.html#autotoc_md332", null ],
      [ "SAVE", "group__race.html#autotoc_md335", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md338", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md341", null ],
      [ "SKILL", "group__race.html#autotoc_md344", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md347", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md350", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md353", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md356", null ],
    [ "Setup", "group__redis.html#autotoc_md357", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md358", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md359", [
      [ "Moving on", "group__redis.html#autotoc_md360", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md361", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md362", null ],
    [ "Sample Include", "group__rename.html#autotoc_md363", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md364", null ],
    [ "Environment Variables", "group__serverlogredirector.html#autotoc_md365", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md366", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md373", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md374", null ],
    [ "Migration", "group__sql.html#autotoc_md378", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md379", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md380", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md381", null ],
      [ "NWNX_SQL_PORT", "group__sql.html#autotoc_md382", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md383", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md384", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md385", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md386", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md387", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md388", null ]
    ] ],
    [ "Environment Variables", "group__threadwatchdog.html#autotoc_md389", null ],
    [ "Environment Variables", "group__tracking.html#autotoc_md390", null ],
    [ "Environment Variables", "group__tweaks.html#autotoc_md391", null ],
    [ "Environment variable values", "group__tweaks.html#autotoc_md392", [
      [ "NWNX_TWEAKS_HIDE_PLAYERS_ON_CHAR_LIST", "group__tweaks.html#autotoc_md393", null ],
      [ "NWNX_TWEAKS_ITEM_CHARGES_COST_MODE", "group__tweaks.html#autotoc_md394", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md395", null ],
    [ "Limitations", "group__webhook.html#autotoc_md401", null ],
    [ "Example usage", "group__webhook.html#autotoc_md402", null ],
    [ "nwnx.nss", "nwnx_8nss.html", "nwnx_8nss" ],
    [ "nwnx_consts.nss", "nwnx__consts_8nss.html", "nwnx__consts_8nss" ],
    [ "nwnx_tests.nss", "nwnx__tests_8nss.html", "nwnx__tests_8nss" ]
];