var dir_b4615358f6508fb1b951d958d300a95c =
[
    [ "Environment Variables", "group__chat.html#autotoc_md15", null ],
    [ "Example", "group__damage.html#autotoc_md16", null ],
    [ "Notes", "group__elc.html#autotoc_md17", null ],
    [ "Environment Variables", "group__elc.html#autotoc_md18", null ],
    [ "Example Script", "group__elc.html#autotoc_md19", null ],
    [ "Notes", "group__experimental.html#autotoc_md20", null ],
    [ "Environment Variables", "group__experimental.html#autotoc_md21", null ],
    [ "Environment Variables", "group__jvm.html#autotoc_md22", null ],
    [ "Environment Variables", "group__lua.html#autotoc_md23", null ],
    [ "Quick start", "group__lua.html#autotoc_md24", [
      [ "Docker", "group__lua.html#autotoc_md25", null ],
      [ "Native", "group__lua.html#autotoc_md26", null ]
    ] ],
    [ "Documentation", "group__lua.html#autotoc_md27", null ],
    [ "Installation and configuration", "group__lua.html#autotoc_md28", null ],
    [ "Notes on Compilation", "group__lua.html#autotoc_md29", null ],
    [ "Note on LuaJIT and extensions", "group__lua.html#autotoc_md30", null ],
    [ "Environment Variables", "group__maxlevel.html#autotoc_md31", null ],
    [ "Required Plugins", "group__maxlevel.html#autotoc_md32", null ],
    [ "Issues", "group__maxlevel.html#autotoc_md33", null ],
    [ "Setup", "group__maxlevel.html#autotoc_md34", null ],
    [ "InfluxDB setup", "group__metrics__influxdb.html#autotoc_md35", null ],
    [ "Environment Variables", "group__metrics__influxdb.html#autotoc_md36", null ],
    [ "How to see sharp?", "group__mono.html#autotoc_md37", null ],
    [ "Remote Debugging", "group__mono.html#autotoc_md38", null ],
    [ "Limitations", "group__mono.html#autotoc_md39", null ],
    [ "Environment Variables", "group__mono.html#autotoc_md40", null ],
    [ "Function Documentation and Examples", "group__player.html#autotoc_md41", null ],
    [ "Environment Variables", "group__profiler.html#autotoc_md43", null ],
    [ "Environmental Variables", "group__race.html#autotoc_md44", null ],
    [ "Required NWNX Plugins", "group__race.html#autotoc_md45", null ],
    [ "Setup", "group__race.html#autotoc_md46", [
      [ "The 2da Method", "group__race.html#autotoc_md47", null ],
      [ "The Scripting Method", "group__race.html#autotoc_md48", null ]
    ] ],
    [ "Racial Modifiers", "group__race.html#autotoc_md49", [
      [ "AB", "group__race.html#autotoc_md50", null ],
      [ "ABVSRACE", "group__race.html#autotoc_md53", null ],
      [ "AC", "group__race.html#autotoc_md56", null ],
      [ "ACVSRACE", "group__race.html#autotoc_md59", null ],
      [ "CONCEALMENT", "group__race.html#autotoc_md62", null ],
      [ "DMGREDUCTION", "group__race.html#autotoc_md65", null ],
      [ "DMGRESIST", "group__race.html#autotoc_md68", null ],
      [ "DMGIMMUNITY", "group__race.html#autotoc_md71", null ],
      [ "FEAT", "group__race.html#autotoc_md74", null ],
      [ "FEATUSAGE", "group__race.html#autotoc_md77", null ],
      [ "IMMUNITY", "group__race.html#autotoc_md80", null ],
      [ "INITIATIVE", "group__race.html#autotoc_md83", null ],
      [ "MOVEMENTSPEED", "group__race.html#autotoc_md86", null ],
      [ "RACE", "group__race.html#autotoc_md89", null ],
      [ "REGENERATION", "group__race.html#autotoc_md92", null ],
      [ "SAVE", "group__race.html#autotoc_md95", null ],
      [ "SAVEVSRACE", "group__race.html#autotoc_md98", null ],
      [ "SAVEVSTYPE", "group__race.html#autotoc_md101", null ],
      [ "SKILL", "group__race.html#autotoc_md104", null ],
      [ "SPELLIMMUNITY", "group__race.html#autotoc_md107", null ],
      [ "SRCHARGEN", "group__race.html#autotoc_md110", null ],
      [ "SRINCLEVEL", "group__race.html#autotoc_md113", null ]
    ] ],
    [ "Hints", "group__redis.html#autotoc_md116", null ],
    [ "Setup", "group__redis.html#autotoc_md117", null ],
    [ "Accessing Redis from nwscript", "group__redis.html#autotoc_md118", null ],
    [ "Getting started with PubSub", "group__redis.html#autotoc_md119", [
      [ "Moving on", "group__redis.html#autotoc_md120", null ]
    ] ],
    [ "Environment Variables", "group__redis.html#autotoc_md121", null ],
    [ "Environment Variables", "group__rename.html#autotoc_md122", null ],
    [ "Sample Include", "group__rename.html#autotoc_md123", null ],
    [ "Environment Variables", "group__ruby.html#autotoc_md124", null ],
    [ "Plugin Sample Usage", "group__skillranks.html#autotoc_md125", null ],
    [ "How to install?", "group__spellchecker.html#autotoc_md132", null ],
    [ "Environment Variables", "group__spellchecker.html#autotoc_md133", null ],
    [ "Migration", "group__sql.html#autotoc_md137", null ],
    [ "Environment Variables", "group__sql.html#autotoc_md138", [
      [ "NWNX_SQL_TYPE", "group__sql.html#autotoc_md139", null ],
      [ "NWNX_SQL_HOST", "group__sql.html#autotoc_md140", null ],
      [ "NWNX_SQL_USERNAME", "group__sql.html#autotoc_md141", null ],
      [ "NWNX_SQL_PASSWORD", "group__sql.html#autotoc_md142", null ],
      [ "NWNX_SQL_DATABASE", "group__sql.html#autotoc_md143", null ],
      [ "NWNX_SQL_QUERY_METRICS", "group__sql.html#autotoc_md144", null ],
      [ "NWNX_SQL_USE_UTF8", "group__sql.html#autotoc_md145", null ],
      [ "NWNX_SQL_CHARACTER_SET", "group__sql.html#autotoc_md146", null ]
    ] ],
    [ "Environment Variables", "group__util.html#autotoc_md150", null ],
    [ "Limitations", "group__webhook.html#autotoc_md156", null ],
    [ "Example usage", "group__webhook.html#autotoc_md157", null ]
];